### ISSUE TITLE
内存泄露问题

### ISSUE THREAD

**Issue by qiuguanyou** [xLong1029/xlong-big-data#1]
通过谷歌浏览器开发者工具-内存 观察有内存泄露

**Comment by xLong1029** [comment]
![image](https://user-images.githubusercontent.com/18066675/226569960-05f23353-2f6d-4f08-993e-2ccafaf0c55d.png)
![image](https://user-images.githubusercontent.com/18066675/226570065-4b23f4a9-b3e8-4e71-88a0-5d4087cb5fb6.png)
![image](https://user-images.githubusercontent.com/18066675/226570571-f46d2625-1a58-4423-a9ad-10f9929f8a5a.png)

跑了30分钟，感觉还行？项目图表、请求用到了很多定时器，加上mock数据一直增加，的确占内存。依据正式环境的使用经验，在凌晨4点（这时候没人看数据）的时候重载页面解决内存占用的问题：
![image](https://user-images.githubusercontent.com/18066675/226575001-d842e0a1-db36-4078-807d-7f5188af548d.png)
